### ISSUE TITLE
This module 'Az.Accounts' may override the existing commands

### ISSUE THREAD

**Issue by martijnvanschie** [SureStacks/AzureAssess#3]
Perhaps not an issue but more a question.
How do i deal with below error message. Not sure i want to override an existing module with an older one.

![image](https://github.com/SureStacks/AzureAssess/assets/8370550/10fbe898-1ee3-43d4-9323-0093d0bd9493)

**Comment by cblomart** [comment]
Hey @martijnvanschie ,

Let's check what is happening there.

Can you tell me if hte modules are already installed maybe at a more recent version?

```PowerShell
get-module -Name Az.Accounts -ListAvailable
```

**Comment by martijnvanschie** [comment]
Hhh, i though i checked this correctly but i used `Find-Module` instead. This searched the online repo :)
Calling `Get-InstalledModule` returns nothing, even without parameters.

Hope this gives some insights.

**Comment by cblomart** [comment]
In this case two things…

if you installed the  « Az » module earlier lets update it: https://learn.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-0.10.0#update-the-azure-powershell-module

otherwise you can use the « -allowclobber »: this will let azure assess install more recent versions of the required modules.

**Comment by martijnvanschie** [comment]
It might have been something with `AzureRM` in PowerShell 7.3.10

I used these steps to uninstall AzureRM and install Az module.
https://learn.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-11.2.0#uninstall-the-azurerm-module

Works now. 

Thanks for the quick reply.
